# action.yml
name: 'Packer Template Validation'
author: 'P. <clone.gleeful135+github@anonaddy.me>'
description: 'Validates a Packer template'
inputs:
  run_init:
    description: 'Indicates if it is necessary to run init'
    required: false
  args:
    description: 'List of extra arguments needed for the validation'
    required: false
    default: ''
  templates_path:
    description: 'Path to Packer templates'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
